### ISSUE TITLE
'|\' や '_\' が入力できない

### ISSUE THREAD

**Issue by Mizuho32** [BOSUKE/USBKeyboard_Hakadorun2#2]
タイトルの通り `|\` や `_\` が入力できません。(Backspaceの左のキーと右Shiftの左のキー)
結構致命的なので対応方法を知りたいです。

lang_noneしてみましたが効果なしでした。
versionは0.0.1です。

**Comment by BOSUKE** [comment]
報告ありがとうございます。

現象の原因は、HIDレポートディスクリプタにてキーコードの範囲を0x00～0x65までに制限してしまっていたからでした。
この状態では、せっかくHakadorun2から問題となっているキーのコードを送ってもPC側でそれを捨てる状況でした。

Release rev0002 (ファームバージョン 0.0.2)で改修します。
（ファームの適用方法等は [README.md](https://github.com/BOSUKE/USBKeyboard_Hakadorun2/blob/main/README.md) に記載します）

**Comment by BOSUKE** [comment]
修正版ファームを公開しました https://github.com/BOSUKE/USBKeyboard_Hakadorun2/releases/tag/rev0002
適用法は [README.md](https://github.com/BOSUKE/USBKeyboard_Hakadorun2/blob/main/README.md) を参照してください。

**Comment by Mizuho32** [comment]
@BOSUKE 対応ありがとうございます。
ちなみにですが、ファーム更新手順中のUSBメモリはFAT32でフォーマットされている必要がありますか?

**Comment by BOSUKE** [comment]
@Mizuho32  はい、FAT32 （またはFAT16） でフォーマットされている必要があります。

**Comment by Mizuho32** [comment]
@BOSUKE ありがとうございます
