### ISSUE TITLE
特殊キー(ボリュームアップなど)が反応しない

### ISSUE THREAD

**Issue by Mizuho32** [BOSUKE/USBKeyboard_Hakadorun2#3]
ボリュームアップなど特殊キーが反応しません。
FNキーを使うタイプのキーボード、ボリュームアップボタンがあるキーボードなど複数試したのですがダメだったのでファームフェアで握りつぶされているのかと思います。

**Comment by BOSUKE** [comment]
ご報告ありがとうございます。

#2 と同件と考えられます。
ただしHakadorun2が対応しているのは、[HID Usage Tables](https://usb.org/sites/default/files/hut1_4.pdf) の　10 Keyboard/Keypad Page (0x07) の Usage IDのみを扱っているため、キーによっては #2 対応後も反応しない可能性があります。（反応しなくてもそれがHakadorun2の仕様です)

**Comment by Mizuho32** [comment]
@BOSUKE 
v0.0.2ファーム更新後も確かに特殊キーは動作しませんでした。
理解がまだ浅いのですが、UsageIDというのは本のp.50付近に記載の内容と関係があり、ここらへんをどうにかするには技術の問題と言うよりお金の問題になってくる、という感じでしょうか?
